### ISSUE TITLE
에어플로우 yaml로 띄울 때 오류:ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.

### ISSUE THREAD

**Issue by hamsunwoo** [pladata-encore/DE32_LAST_DANCE#24]
에어플로우를 yaml로 띄우고 PythonVirtualOperator를 사용하려 하는데 'ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.' 에러가 발생합니다. 여러가지 시도를 해보았는데 해결이 되지않아 이슈올립니다.

오류메세지
```
[2024-11-21 02:44:46,029] {process_utils.py:135} INFO - Executing cmd: virtualenv /tmp/venv17g2mznw
[2024-11-21 02:44:46,035] {process_utils.py:137} INFO - Output:
[2024-11-21 02:44:46,619] {process_utils.py:141} INFO - created virtual environment CPython3.6.15.final.0-64 in 447ms
[2024-11-21 02:44:46,619] {process_utils.py:141} INFO -   creator CPython3Posix(dest=/tmp/venv17g2mznw, clear=False, no_vcs_ignore=False, global=False)
[2024-11-21 02:44:46,620] {process_utils.py:141} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/tmp/tmphz55ng6i)
[2024-11-21 02:44:46,620] {process_utils.py:141} INFO -     added seed packages: pip==21.0.1, setuptools==56.0.0, wheel==0.36.2
[2024-11-21 02:44:46,621] {process_utils.py:141} INFO -   activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
[2024-11-21 02:44:46,634] {process_utils.py:135} INFO - Executing cmd: /tmp/venv17g2mznw/bin/pip install git+https://github.com/Team1-TU-tech/crawling.git@0.3.2/dev/yes24
[2024-11-21 02:44:46,641] {process_utils.py:137} INFO - Output:
[2024-11-21 02:44:47,318] {process_utils.py:141} INFO - WARNING: The directory '/home/airflow/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
[2024-11-21 02:44:47,318] {process_utils.py:141} INFO - ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
[2024-11-21 02:44:47,840] {process_utils.py:141} INFO - WARNING: You are using pip version 21.0.1; however, version 21.3.1 is available.
[2024-11-21 02:44:47,840] {process_utils.py:141} INFO - You should consider upgrading via the '/tmp/venv17g2mznw/bin/python -m pip install --upgrade pip' command.
```

**Comment by hamsunwoo** [comment]
- https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html

**Comment by dMario24** [comment]
진행 상황을 기술하면 좀더 디버깅 하기 좋을거 같아요.
- https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html 해당 문서에 기인하여 설치한 것으로 보이며,

- 로그 상 virtualenv 접근 권한 문제로 보이며, 위 가이드와 같이 설치 되면 관련 오류가 발생하지 않습니다. 아래 로그 참조

```
320ff9130a0d
*** Found local files:
***   * /opt/airflow/logs/dag_id=yes24_to_MongoDB/run_id=manual__2024-11-21T05:25:26.440992+00:00/task_id=extract/attempt=1.log
[2024-11-21, 05:25:31 UTC] {local_task_job_runner.py:123} ▶ Pre task execution logs
[2024-11-21, 05:25:33 UTC] {baseoperator.py:416} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2024-11-21, 05:25:33 UTC] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvj6ne93ah --python=python
[2024-11-21, 05:25:33 UTC] {process_utils.py:190} INFO - Output:
[2024-11-21, 05:25:35 UTC] {process_utils.py:194} INFO - created virtual environment CPython3.12.7.final.0-64 in 896ms
[2024-11-21, 05:25:35 UTC] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venvj6ne93ah, clear=False, no_vcs_ignore=False, global=False)
[2024-11-21, 05:25:35 UTC] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-21, 05:25:35 UTC] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2024-11-21, 05:25:35 UTC] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-21, 05:25:35 UTC] {process_utils.py:186} INFO - Executing cmd: /tmp/venvj6ne93ah/bin/pip install -r /tmp/venvj6ne93ah/requirements.txt
[2024-11-21, 05:25:35 UTC] {process_utils.py:190} INFO - Output:
[2024-11-21, 05:25:37 UTC] {process_utils.py:194} INFO - Collecting git+https://github.com/Team1-TU-tech/crawling.git@0.3.2/dev/yes24 (from -r /tmp/venvj6ne93ah/requirements.txt (line 1))
[2024-11-21, 05:25:37 UTC] {process_utils.py:194} INFO -   Cloning https://github.com/Team1-TU-tech/crawling.git (to revision 0.3.2/dev/yes24) to /tmp/pip-req-build-jzazrjve
[2024-11-21, 05:25:37 UTC] {process_utils.py:194} INFO -   ERROR: Error [Errno 13] Permission denied: 'git' while executing command git version
[2024-11-21, 05:25:37 UTC] {process_utils.py:194} INFO - ERROR: No permission to execute 'git' - install it locally, globally (ask admin), or check your PATH. See possible solutions at https://pip.pypa.io/en/latest/reference/pip_freeze/#fixing-permission-denied.
[2024-11-21, 05:25:37 UTC] {taskinstance.py:3311} ERROR - Task failed with exception
```

- 다만 GIT 이 설치 되어 있지 않아 WORKER 컨테이너에 GIT 을 설치해 주면 정상 동작합니다. 아래 로그에서 보이는 부분은 DAG 코드상 오류로 보입니다. 코드는 별도 수정 바랍니다.

<details>
    <summary>로그 보기</summary>

```
320ff9130a0d
*** Found local files:
***   * /opt/airflow/logs/dag_id=yes24_to_MongoDB/run_id=manual__2024-11-21T05:25:26.440992+00:00/task_id=extract/attempt=2.log
[2024-11-21, 05:28:53 UTC] {local_task_job_runner.py:123} ▶ Pre task execution logs
[2024-11-21, 05:28:53 UTC] {baseoperator.py:416} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2024-11-21, 05:28:53 UTC] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venv2b8nsx8k --python=python
[2024-11-21, 05:28:53 UTC] {process_utils.py:190} INFO - Output:
[2024-11-21, 05:28:54 UTC] {process_utils.py:194} INFO - created virtual environment CPython3.12.7.final.0-64 in 305ms
[2024-11-21, 05:28:54 UTC] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venv2b8nsx8k, clear=False, no_vcs_ignore=False, global=False)
[2024-11-21, 05:28:54 UTC] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-21, 05:28:54 UTC] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2024-11-21, 05:28:54 UTC] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-21, 05:28:54 UTC] {process_utils.py:186} INFO - Executing cmd: /tmp/venv2b8nsx8k/bin/pip install -r /tmp/venv2b8nsx8k/requirements.txt
[2024-11-21, 05:28:54 UTC] {process_utils.py:190} INFO - Output:
[2024-11-21, 05:28:56 UTC] {process_utils.py:194} INFO - Collecting git+https://github.com/Team1-TU-tech/crawling.git@0.3.2/dev/yes24 (from -r /tmp/venv2b8nsx8k/requirements.txt (line 1))
[2024-11-21, 05:28:56 UTC] {process_utils.py:194} INFO -   Cloning https://github.com/Team1-TU-tech/crawling.git (to revision 0.3.2/dev/yes24) to /tmp/pip-req-build-kbrh6nak
[2024-11-21, 05:28:56 UTC] {process_utils.py:194} INFO -   Running command git clone --filter=blob:none --quiet https://github.com/Team1-TU-tech/crawling.git /tmp/pip-req-build-kbrh6nak
[2024-11-21, 05:28:57 UTC] {process_utils.py:194} INFO -   Running command git checkout -b 0.3.2/dev/yes24 --track origin/0.3.2/dev/yes24
[2024-11-21, 05:28:58 UTC] {process_utils.py:194} INFO -   Switched to a new branch '0.3.2/dev/yes24'
[2024-11-21, 05:28:58 UTC] {process_utils.py:194} INFO -   branch '0.3.2/dev/yes24' set up to track 'origin/0.3.2/dev/yes24'.
[2024-11-21, 05:28:58 UTC] {process_utils.py:194} INFO -   Resolved https://github.com/Team1-TU-tech/crawling.git to commit 2be1d9fc32e127bbadc1a1614bf1dbb1bd2d7f13
[2024-11-21, 05:28:58 UTC] {process_utils.py:194} INFO -   Installing build dependencies: started
[2024-11-21, 05:29:00 UTC] {process_utils.py:194} INFO -   Installing build dependencies: finished with status 'done'
[2024-11-21, 05:29:00 UTC] {process_utils.py:194} INFO -   Getting requirements to build wheel: started
[2024-11-21, 05:29:01 UTC] {process_utils.py:194} INFO -   Getting requirements to build wheel: finished with status 'done'
[2024-11-21, 05:29:01 UTC] {process_utils.py:194} INFO -   Preparing metadata (pyproject.toml): started
[2024-11-21, 05:29:02 UTC] {process_utils.py:194} INFO -   Preparing metadata (pyproject.toml): finished with status 'done'
[2024-11-21, 05:29:02 UTC] {process_utils.py:194} INFO - Collecting selenium>=4.26.1 (from crawling==0.3.2->-r /tmp/venv2b8nsx8k/requirements.txt (line 1))
[2024-11-21, 05:29:02 UTC] {process_utils.py:194} INFO -   Downloading selenium-4.26.1-py3-none-any.whl.metadata (7.1 kB)
[2024-11-21, 05:29:02 UTC] {process_utils.py:194} INFO - Collecting webdriver-manager>=4.0.2 (from crawling==0.3.2->-r /tmp/venv2b8nsx8k/requirements.txt (line 1))
[2024-11-21, 05:29:02 UTC] {process_utils.py:194} INFO -   Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl.metadata (12 kB)
[2024-11-21, 05:29:02 UTC] {process_utils.py:194} INFO - Collecting python-dateutil>=2.9.0.post0 (from crawling==0.3.2->-r /tmp/venv2b8nsx8k/requirements.txt (line 1))
[2024-11-21, 05:29:02 UTC] {process_utils.py:194} INFO -   Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
[2024-11-21, 05:29:02 UTC] {process_utils.py:194} INFO - Collecting six>=1.5 (from python-dateutil>=2.9.0.post0->crawling==0.3.2->-r /tmp/venv2b8nsx8k/requirements.txt (line 1))
[2024-11-21, 05:29:02 UTC] {process_utils.py:194} INFO -   Downloading six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
[2024-11-21, 05:29:02 UTC] {process_utils.py:194} INFO - Collecting urllib3<3,>=1.26 (from urllib3[socks]<3,>=1.26->selenium>=4.26.1->crawling==0.3.2->-r /tmp/venv2b8nsx8k/requirements.txt (line 1))
[2024-11-21, 05:29:02 UTC] {process_utils.py:194} INFO -   Downloading urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
[2024-11-21, 05:29:02 UTC] {process_utils.py:194} INFO - Collecting trio~=0.17 (from selenium>=4.26.1->crawling==0.3.2->-r /tmp/venv2b8nsx8k/requirements.txt (line 1))
[2024-11-21, 05:29:02 UTC] {process_utils.py:194} INFO -   Downloading trio-0.27.0-py3-none-any.whl.metadata (8.6 kB)
[2024-11-21, 05:29:02 UTC] {process_utils.py:194} INFO - Collecting trio-websocket~=0.9 (from selenium>=4.26.1->crawling==0.3.2->-r /tmp/venv2b8nsx8k/requirements.txt (line 1))
[2024-11-21, 05:29:02 UTC] {process_utils.py:194} INFO -   Downloading trio_websocket-0.11.1-py3-none-any.whl.metadata (4.7 kB)
[2024-11-21, 05:29:02 UTC] {process_utils.py:194} INFO - Collecting certifi>=2021.10.8 (from selenium>=4.26.1->crawling==0.3.2->-r /tmp/venv2b8nsx8k/requirements.txt (line 1))
[2024-11-21, 05:29:02 UTC] {process_utils.py:194} INFO -   Downloading certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
[2024-11-21, 05:29:02 UTC] {process_utils.py:194} INFO - Collecting typing_extensions~=4.9 (from selenium>=4.26.1->crawling==0.3.2->-r /tmp/venv2b8nsx8k/requirements.txt (line 1))
[2024-11-21, 05:29:02 UTC] {process_utils.py:194} INFO -   Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
[2024-11-21, 05:29:02 UTC] {process_utils.py:194} INFO - Collecting websocket-client~=1.8 (from selenium>=4.26.1->crawling==0.3.2->-r /tmp/venv2b8nsx8k/requirements.txt (line 1))
[2024-11-21, 05:29:02 UTC] {process_utils.py:194} INFO -   Downloading websocket_client-1.8.0-py3-none-any.whl.metadata (8.0 kB)
[2024-11-21, 05:29:02 UTC] {process_utils.py:194} INFO - Collecting requests (from webdriver-manager>=4.0.2->crawling==0.3.2->-r /tmp/venv2b8nsx8k/requirements.txt (line 1))
[2024-11-21, 05:29:02 UTC] {process_utils.py:194} INFO -   Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
[2024-11-21, 05:29:02 UTC] {process_utils.py:194} INFO - Collecting python-dotenv (from webdriver-manager>=4.0.2->crawling==0.3.2->-r /tmp/venv2b8nsx8k/requirements.txt (line 1))
[2024-11-21, 05:29:02 UTC] {process_utils.py:194} INFO -   Downloading python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
[2024-11-21, 05:29:03 UTC] {process_utils.py:194} INFO - Collecting packaging (from webdriver-manager>=4.0.2->crawling==0.3.2->-r /tmp/venv2b8nsx8k/requirements.txt (line 1))
[2024-11-21, 05:29:03 UTC] {process_utils.py:194} INFO -   Downloading packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
[2024-11-21, 05:29:03 UTC] {process_utils.py:194} INFO - Collecting attrs>=23.2.0 (from trio~=0.17->selenium>=4.26.1->crawling==0.3.2->-r /tmp/venv2b8nsx8k/requirements.txt (line 1))
[2024-11-21, 05:29:03 UTC] {process_utils.py:194} INFO -   Downloading attrs-24.2.0-py3-none-any.whl.metadata (11 kB)
[2024-11-21, 05:29:03 UTC] {process_utils.py:194} INFO - Collecting sortedcontainers (from trio~=0.17->selenium>=4.26.1->crawling==0.3.2->-r /tmp/venv2b8nsx8k/requirements.txt (line 1))
[2024-11-21, 05:29:03 UTC] {process_utils.py:194} INFO -   Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
[2024-11-21, 05:29:03 UTC] {process_utils.py:194} INFO - Collecting idna (from trio~=0.17->selenium>=4.26.1->crawling==0.3.2->-r /tmp/venv2b8nsx8k/requirements.txt (line 1))
[2024-11-21, 05:29:03 UTC] {process_utils.py:194} INFO -   Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
[2024-11-21, 05:29:03 UTC] {process_utils.py:194} INFO - Collecting outcome (from trio~=0.17->selenium>=4.26.1->crawling==0.3.2->-r /tmp/venv2b8nsx8k/requirements.txt (line 1))
[2024-11-21, 05:29:03 UTC] {process_utils.py:194} INFO -   Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
[2024-11-21, 05:29:03 UTC] {process_utils.py:194} INFO - Collecting sniffio>=1.3.0 (from trio~=0.17->selenium>=4.26.1->crawling==0.3.2->-r /tmp/venv2b8nsx8k/requirements.txt (line 1))
[2024-11-21, 05:29:03 UTC] {process_utils.py:194} INFO -   Downloading sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
[2024-11-21, 05:29:03 UTC] {process_utils.py:194} INFO - Collecting wsproto>=0.14 (from trio-websocket~=0.9->selenium>=4.26.1->crawling==0.3.2->-r /tmp/venv2b8nsx8k/requirements.txt (line 1))
[2024-11-21, 05:29:03 UTC] {process_utils.py:194} INFO -   Downloading wsproto-1.2.0-py3-none-any.whl.metadata (5.6 kB)
[2024-11-21, 05:29:03 UTC] {process_utils.py:194} INFO - Collecting pysocks!=1.5.7,<2.0,>=1.5.6 (from urllib3[socks]<3,>=1.26->selenium>=4.26.1->crawling==0.3.2->-r /tmp/venv2b8nsx8k/requirements.txt (line 1))
[2024-11-21, 05:29:03 UTC] {process_utils.py:194} INFO -   Downloading PySocks-1.7.1-py3-none-any.whl.metadata (13 kB)
[2024-11-21, 05:29:03 UTC] {process_utils.py:194} INFO - Collecting charset-normalizer<4,>=2 (from requests->webdriver-manager>=4.0.2->crawling==0.3.2->-r /tmp/venv2b8nsx8k/requirements.txt (line 1))
[2024-11-21, 05:29:03 UTC] {process_utils.py:194} INFO -   Downloading charset_normalizer-3.4.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (34 kB)
[2024-11-21, 05:29:03 UTC] {process_utils.py:194} INFO - Collecting h11<1,>=0.9.0 (from wsproto>=0.14->trio-websocket~=0.9->selenium>=4.26.1->crawling==0.3.2->-r /tmp/venv2b8nsx8k/requirements.txt (line 1))
[2024-11-21, 05:29:03 UTC] {process_utils.py:194} INFO -   Downloading h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)
[2024-11-21, 05:29:03 UTC] {process_utils.py:194} INFO - Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
[2024-11-21, 05:29:03 UTC] {process_utils.py:194} INFO - Downloading selenium-4.26.1-py3-none-any.whl (9.7 MB)
[2024-11-21, 05:29:04 UTC] {process_utils.py:194} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 26.9 MB/s eta 0:00:00
[2024-11-21, 05:29:04 UTC] {process_utils.py:194} INFO - Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl (27 kB)
[2024-11-21, 05:29:04 UTC] {process_utils.py:194} INFO - Downloading certifi-2024.8.30-py3-none-any.whl (167 kB)
[2024-11-21, 05:29:04 UTC] {process_utils.py:194} INFO - Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
[2024-11-21, 05:29:04 UTC] {process_utils.py:194} INFO - Downloading trio-0.27.0-py3-none-any.whl (481 kB)
[2024-11-21, 05:29:04 UTC] {process_utils.py:194} INFO - Downloading trio_websocket-0.11.1-py3-none-any.whl (17 kB)
[2024-11-21, 05:29:04 UTC] {process_utils.py:194} INFO - Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
[2024-11-21, 05:29:04 UTC] {process_utils.py:194} INFO - Downloading urllib3-2.2.3-py3-none-any.whl (126 kB)
[2024-11-21, 05:29:04 UTC] {process_utils.py:194} INFO - Downloading websocket_client-1.8.0-py3-none-any.whl (58 kB)
[2024-11-21, 05:29:04 UTC] {process_utils.py:194} INFO - Downloading packaging-24.2-py3-none-any.whl (65 kB)
[2024-11-21, 05:29:04 UTC] {process_utils.py:194} INFO - Downloading python_dotenv-1.0.1-py3-none-any.whl (19 kB)
[2024-11-21, 05:29:04 UTC] {process_utils.py:194} INFO - Downloading requests-2.32.3-py3-none-any.whl (64 kB)
[2024-11-21, 05:29:04 UTC] {process_utils.py:194} INFO - Downloading attrs-24.2.0-py3-none-any.whl (63 kB)
[2024-11-21, 05:29:04 UTC] {process_utils.py:194} INFO - Downloading charset_normalizer-3.4.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (143 kB)
[2024-11-21, 05:29:04 UTC] {process_utils.py:194} INFO - Downloading idna-3.10-py3-none-any.whl (70 kB)
[2024-11-21, 05:29:04 UTC] {process_utils.py:194} INFO - Downloading PySocks-1.7.1-py3-none-any.whl (16 kB)
[2024-11-21, 05:29:04 UTC] {process_utils.py:194} INFO - Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
[2024-11-21, 05:29:04 UTC] {process_utils.py:194} INFO - Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
[2024-11-21, 05:29:04 UTC] {process_utils.py:194} INFO - Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
[2024-11-21, 05:29:04 UTC] {process_utils.py:194} INFO - Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
[2024-11-21, 05:29:04 UTC] {process_utils.py:194} INFO - Downloading h11-0.14.0-py3-none-any.whl (58 kB)
[2024-11-21, 05:29:04 UTC] {process_utils.py:194} INFO - Building wheels for collected packages: crawling
[2024-11-21, 05:29:04 UTC] {process_utils.py:194} INFO -   Building wheel for crawling (pyproject.toml): started
[2024-11-21, 05:29:05 UTC] {process_utils.py:194} INFO -   Building wheel for crawling (pyproject.toml): finished with status 'done'
[2024-11-21, 05:29:05 UTC] {process_utils.py:194} INFO -   Created wheel for crawling: filename=crawling-0.3.2-py3-none-any.whl size=6943 sha256=32517b752743bc69ba79becd56a22d05af2cb623fe1a831f58a53ff48a30390e
[2024-11-21, 05:29:05 UTC] {process_utils.py:194} INFO -   Stored in directory: /tmp/pip-ephem-wheel-cache-y1qyyl7b/wheels/f2/5a/5c/7f20628df207cf0c529d3fc022e51e23c728831a7aee2ebfff
[2024-11-21, 05:29:05 UTC] {process_utils.py:194} INFO - Successfully built crawling
[2024-11-21, 05:29:05 UTC] {process_utils.py:194} INFO - Installing collected packages: sortedcontainers, websocket-client, urllib3, typing_extensions, sniffio, six, python-dotenv, pysocks, packaging, idna, h11, charset-normalizer, certifi, attrs, wsproto, requests, python-dateutil, outcome, webdriver-manager, trio, trio-websocket, selenium, crawling
[2024-11-21, 05:29:07 UTC] {process_utils.py:194} INFO - Successfully installed attrs-24.2.0 certifi-2024.8.30 charset-normalizer-3.4.0 crawling-0.3.2 h11-0.14.0 idna-3.10 outcome-1.3.0.post0 packaging-24.2 pysocks-1.7.1 python-dateutil-2.9.0.post0 python-dotenv-1.0.1 requests-2.32.3 selenium-4.26.1 six-1.16.0 sniffio-1.3.1 sortedcontainers-2.4.0 trio-0.27.0 trio-websocket-0.11.1 typing_extensions-4.12.2 urllib3-2.2.3 webdriver-manager-4.0.2 websocket-client-1.8.0 wsproto-1.2.0
[2024-11-21, 05:29:07 UTC] {process_utils.py:186} INFO - Executing cmd: /tmp/venv2b8nsx8k/bin/python /tmp/venv-callyqp2ye_g/script.py /tmp/venv-callyqp2ye_g/script.in /tmp/venv-callyqp2ye_g/script.out /tmp/venv-callyqp2ye_g/string_args.txt /tmp/venv-callyqp2ye_g/termination.log
[2024-11-21, 05:29:07 UTC] {process_utils.py:190} INFO - Output:
[2024-11-21, 05:29:08 UTC] {process_utils.py:194} INFO - Traceback (most recent call last):
[2024-11-21, 05:29:08 UTC] {process_utils.py:194} INFO -   File "/tmp/venv-callyqp2ye_g/script.py", line 48, in <module>
[2024-11-21, 05:29:08 UTC] {process_utils.py:194} INFO -     res = get_data(*arg_dict["args"], **arg_dict["kwargs"])
[2024-11-21, 05:29:08 UTC] {process_utils.py:194} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-21, 05:29:08 UTC] {process_utils.py:194} INFO -   File "/tmp/venv-callyqp2ye_g/script.py", line 19, in get_data
[2024-11-21, 05:29:08 UTC] {process_utils.py:194} INFO -     from crawling.crawler import scrap_data
[2024-11-21, 05:29:08 UTC] {process_utils.py:194} INFO -   File "/tmp/venv2b8nsx8k/lib/python3.12/site-packages/crawling/crawler.py", line 8, in <module>
[2024-11-21, 05:29:08 UTC] {process_utils.py:194} INFO -     from links import get_link  # 링크를 가져오는 함수
[2024-11-21, 05:29:08 UTC] {process_utils.py:194} INFO -     ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-21, 05:29:08 UTC] {process_utils.py:194} INFO - ModuleNotFoundError: No module named 'links'
[2024-11-21, 05:29:08 UTC] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 870, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 588, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
No module named 'links'
[2024-11-21, 05:29:08 UTC] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-21, 05:29:08 UTC] {logging_mixin.py:190} INFO - Task start:2024-11-21 05:28:53.708574+00:00 end:2024-11-21 05:29:08.338028+00:00 duration:14.629454
[2024-11-21, 05:29:08 UTC] {logging_mixin.py:190} INFO - Task:<Task(PythonVirtualenvOperator): extract> dag:<DAG: yes24_to_MongoDB> dagrun:<DagRun yes24_to_MongoDB @ 2024-11-21 05:25:26.440992+00:00: manual__2024-11-21T05:25:26.440992+00:00, state:running, queued_at: 2024-11-21 05:25:26.456750+00:00. externally triggered: True>
[2024-11-21, 05:29:08 UTC] {logging_mixin.py:190} INFO - Failure caused by Process returned non-zero exit status 1.
No module named 'links'
[2024-11-21, 05:29:08 UTC] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=yes24_to_MongoDB, task_id=extract, run_id=manual__2024-11-21T05:25:26.440992+00:00, execution_date=20241121T052526, start_date=20241121T052853, end_date=20241121T052908
[2024-11-21, 05:29:08 UTC] {taskinstance.py:340} ▶ Post task execution logs
```

</details>

**Comment by dMario24** [comment]
그리고 제목도 좀 수행했어요

#전
- 에어플로우 yaml로 띄울 때 오류:ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.

# 후
- docker compose 로 airflow 구축  시  virtualenv 문제
