### ISSUE TITLE
airflow 타임아웃 이슈

### ISSUE THREAD

**Issue by hahahellooo** [pladata-encore/DE32_LAST_DANCE#40]
s3에 저장된 html 파일을 읽고 필요한 데이터만 추출 후 kafka를 통해 mongodb에 저장되는 프로세스로 airflow를 사용하고 있습니다.
파일의 수가 60개 이상이면 timeout error가 발생해서 timesleep을 계속 추가하고 있는데 혹시 다른 해결방법이 있는지, 
해결 방향성이 이게 맞는건지 문의 드리고자 합니다. 
```
[2024-12-05, 02:48:16 UTC] {timeout.py:68} ERROR - Process timed out, PID: 20091
[2024-12-05, 02:50:35 UTC] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-12-05, 02:50:35 UTC] {local_task_job_runner.py:245} ▲▲▲ Log group end
[2024-12-05, 02:50:35 UTC] {process_utils.py:132} INFO - Sending 15 to group 20091. PIDs of all processes in the group: [20168, 33518, 33524, 33530, 33533, 33555, 33556, 33613, 33638, 33554, 20091]
[2024-12-05, 02:50:35 UTC] {process_utils.py:87} INFO - Sending the signal 15 to group 20091
[2024-12-05, 02:50:36 UTC] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-05, 02:50:36 UTC] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 193, in execute_in_subprocess_with_kwargs
    for line in iter(proc.stdout.readline, b""):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: Timeout, PID: 20091
```

**Comment by dMario24** [comment]
파일의 수가 60개 - html 원본 파일

**Comment by dMario24** [comment]
# 타입아웃
- 카카오맵 API 를 사용함
- 60 ~ 70번 사이 호출하면 해당 API 에서 타임아웃 에러가 날 듯하다.

**Comment by dMario24** [comment]
원본로그를 보니 카프카 커넥션 문제로 보임
프로듀서를 파일 하나 처리 시 만들지 말고 전역으로 만들어서 테스트 해보기
또는 프로듀서를 클로즈 해보기
