### ISSUE TITLE
[Airflow] 도커환경 Airflow에서 외부 파이썬 모듈(파일)이 실행이 안되는 문제

### ISSUE THREAD

**Issue by rlaehgus97** [pladata-encore/DE32_LAST_DANCE#46]
### [목표]
link_crawling.py라는 채용공고 사이트 크롤링 python 파일이 있음. 
이 파일은 airflow webserver docker container내에서 opt/airflow/plugins/crawling 디렉토리 안에 위치하고 있음. 해당 크롤링 파이썬 파일은 자신이 있는 디렉토리에서 jumpit, incruit, wanted 디렉토리를 생성하고 그안에 스크랩핑한 url들을 모아놓는 log 파일을 생성. (나머지 메소드들은 s3에 url을 저장합니다)
```
.
└── opt/
    └── airflow/
        ├── dags/
        │   └── dag.py
        └── plugins/
            ├── link_crawling.py
            ├── post_crawling.py
            ├── incruit/
            │   └── 20241211.log
            ├── jumpit/
            │   └── 20241211.log
            └── wanted/
                └── 20241211.log
```

### [문제점]
1. docker container 내에서 jumpit과 같은 디렉토리 생성및 log 파일도 생성이 안됨. link_crawling.py를 못 읽는다고 하기에는 해당 파이썬 main method에 있는 print문들은 정상적으로 실행이 됨. 

2. 아래와 같이 served log를 못읽는 문제가 발생, 이 문제가 airflow log ui에서 코드가 돌아가는 중에 갑자기 이렇게 변경
![image](https://github.com/user-attachments/assets/c1c06ec2-3674-4404-a429-6cc421e98ab1)

<details>
<summary>airflow 로그 전문</summary>

```
airflow-webserver  | [2024-12-11T03:33:15.457+0000] {file_task_handler.py:524} ERROR - Could not read served logs
airflow-webserver  | Traceback (most recent call last):
airflow-webserver  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
airflow-webserver  |     yield
airflow-webserver  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpcore/backends/sync.py", line 94, in connect_tcp
airflow-webserver  |     sock = socket.create_connection(
airflow-webserver  |   File "/usr/local/lib/python3.10/socket.py", line 824, in create_connection
airflow-webserver  |     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
airflow-webserver  |   File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
airflow-webserver  |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
airflow-webserver  | socket.gaierror: [Errno -3] Temporary failure in name resolution
airflow-webserver  |
airflow-webserver  | During handling of the above exception, another exception occurred:
airflow-webserver  |
airflow-webserver  | Traceback (most recent call last):
airflow-webserver  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
airflow-webserver  |     yield
airflow-webserver  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 218, in handle_request
airflow-webserver  |     resp = self._pool.handle_request(req)
airflow-webserver  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 253, in handle_request
airflow-webserver  |     raise exc
airflow-webserver  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 237, in handle_request
airflow-webserver  |     response = connection.handle_request(request)
airflow-webserver  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 86, in handle_request
airflow-webserver  |     raise exc
airflow-webserver  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 63, in handle_request
airflow-webserver  |     stream = self._connect(request)
airflow-webserver  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 111, in _connect
airflow-webserver  |     stream = self._network_backend.connect_tcp(**kwargs)
airflow-webserver  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpcore/backends/sync.py", line 93, in connect_tcp
airflow-webserver  |     with map_exceptions(exc_map):
airflow-webserver  |   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
airflow-webserver  |     self.gen.throw(typ, value, traceback)
airflow-webserver  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
airflow-webserver  |     raise to_exc(exc)
airflow-webserver  | httpcore.ConnectError: [Errno -3] Temporary failure in name resolution
airflow-webserver  |
airflow-webserver  | The above exception was the direct cause of the following exception:
airflow-webserver  |
airflow-webserver  | Traceback (most recent call last):
airflow-webserver  |   File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/log/file_task_handler.py", line 507, in _read_from_logs_server
airflow-webserver  |     response = _fetch_logs_from_service(url, rel_path)
airflow-webserver  |   File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/log/file_task_handler.py", line 90, in _fetch_logs_from_service
airflow-webserver  |     response = httpx.get(
airflow-webserver  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_api.py", line 189, in get
airflow-webserver  |     return request(
airflow-webserver  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_api.py", line 100, in request
airflow-webserver  |     return client.request(
airflow-webserver  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_client.py", line 821, in request
airflow-webserver  |     return self.send(request, auth=auth, follow_redirects=follow_redirects)
airflow-webserver  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_client.py", line 908, in send
airflow-webserver  |     response = self._send_handling_auth(
airflow-webserver  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_client.py", line 936, in _send_handling_auth
airflow-webserver  |     response = self._send_handling_redirects(
airflow-webserver  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_client.py", line 973, in _send_handling_redirects
airflow-webserver  |     response = self._send_single_request(request)
airflow-webserver  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_client.py", line 1009, in _send_single_request
airflow-webserver  |     response = transport.handle_request(request)
airflow-webserver  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 217, in handle_request
airflow-webserver  |     with map_httpcore_exceptions():
airflow-webserver  |   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
airflow-webserver  |     self.gen.throw(typ, value, traceback)
airflow-webserver  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
airflow-webserver  |     raise mapped_exc(message) from exc
airflow-webserver  | httpx.ConnectError: [Errno -3] Temporary failure in name resolution
```
</details>
>> docker-compose.yaml에 airflow-scheduler: restart: always 를 붙여주니 link_crawling.py는 실행되지만 위처럼 로그는 계속 served log를 읽지 못한다고 출력이 됩니다.
[Dockerfile](https://github.com/DE32FinalTeam2/FinalRepo/blob/dev/crawling/all-kdh-test/airflow/Dockerfile-airflow)
[docker-compose.yaml](https://github.com/DE32FinalTeam2/FinalRepo/blob/dev/crawling/all-kdh-test/docker-compose.yaml)
[link_crawling.py](https://github.com/DE32FinalTeam2/FinalRepo/blob/dev/crawling/all-kdh-test/airflow/plugins/crawling/link_crawling.py)

로컬과 도커컨테이너 내에서 직접 파이썬 파일을 실행시켰을때는 잘 되는것이 왜 에어플로우에서는 실행이 되다 끊기는지, 어디서부터 문제를 접근해야할지 알려주시면 감사하겠습니다.

**Comment by dMario24** [comment]
@rlaehgus97 해결 되셨나요? 오프로 오지 않으셔서 안보고 있엇네요. 진행 중이면 오셔셔 같이봐요.
